version: 2.1

jobs:

  install_and_zip:
    docker:
      - image: cimg/node:22.12.0  
    working_directory: ~/repo
    steps:
      - checkout 
      - run:
          name: Install dependencies
          command: |
            npm install --save-dev env-cmd
            npm install
      - run:
          name: Build project
          command: |
            npm run build:prod
      - run:
          name: Zip the project
          command: |
            cd build
            zip -r app.zip .
            mv app.zip ..
            cd ..
      - persist_to_workspace:
          root: .
          paths:
            - app.zip 

  deploy:
    docker:
      - image: circleci/python:3.8 
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install sshpass and scp
          command: |
            sudo apt-get update
            sudo apt-get install -y sshpass zip
      - run:
          name: Check directory
          command: |
            ls -l
      - run:
          name: Transfer ZIP file to server using SCP
          command: |
            # Use sshpass for password-based SCP transfer
            sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@103.179.191.223 "rm -rf /var/www/spacehub && mkdir /var/www/spacehub"
            sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null app.zip root@103.179.191.223:/var/www/spacehub
      - run:
          name: Create deploy script on CircleCI and transfer to VPS
          command: |
            sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@103.179.191.223 '
              cd /var/www/spacehub;
              unzip -o app.zip;
            '

workflows:
  version: 2
  deploy:
    jobs:
      - install_and_zip:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - install_and_zip
          filters:
            branches:
              only:
                - main 

